//Get All User
GET http://localhost:5000/users

//Get All Job
###
GET http://localhost:5000/jobs?search_query=Fajar&page=0&limit=5


//Get Single User 
###
GET http://localhost:5000/users/b4a3292e-b5f4-4836-bbbb-abebbd77c5dc

//Get Single Job 
###
GET http://localhost:5000/jobs/c7129cab-dbab-4a5c-8884-3a9aebc4f974

//Create User
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "email": "Yowisjar@gmail.com",
    "password": "12345678",
    "confPassword": "12345678"
}

//Create Job
###
POST http://localhost:5000/jobs
Content-Type: application/json

{
    "companyName": "PT. Arvitech Mega Solusi",
    "companyAddress": "Jakarta Pusat",
    "salary": "RP. 2 - 4 juta",
    "jobRole": "Senior Programmer",
    "jobLevel": "junior",
    "jobType": "programmer",
    "jobDescription": "PT. Arvitech Mega Solusi, Driven by technology powered business innovation and committed to bridge the gap between technology and business needs. ARVITECH empowering business by building, integrating, and providing IT ...",
    "education": "Diploma/D1/D2/D3, Sarjana / S1",
    "industry": "programmer"
    
}

###
POST http://localhost:5000/locations
Content-Type: application/json

{
    "name": "Bekasi"
}

//Update User
###
PATCH http://localhost:5000/users/78c50742-ee71-42ea-8a4e-a6e9f91fe58b
Content-Type: application/json

{
    "username": "Yowis",
    "nohp": "085882046322",
    "status": "Belum Menikah",
    "instagramUrl": "https://www.instagram.com/yowisjar/",
    "facebookUrl": "https://www.facebook.com/fajar.p.herianto.3"
}

//Update Job
###
PATCH http://localhost:5000/jobs/1
Content-Type: application/json

{
    "companyName": "PT.Yowisjar",
    "companyAddress": "Bandung",
    "salary": "RP. 5 - 9 juta",
    "jobRole": "programmer",
    "jobLevel": "junior",
    "jobType": "programmer",
    "jobDescription": "harus udah jago ngoding",
    "education": "S1",
    "industry": "programmer"
}

###
//Cek Akun
GET http://localhost:5000/me

###
//Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Fajar@gmail.com",
    "password": "12345678"
}

//Delete User
###
DELETE http://localhost:5000/users/286c9630-04a6-42f1-806b-e9624b4078c3

//Delete User
###
DELETE http://localhost:5000/jobs/1

//Logout User
###
DELETE http://localhost:5000/logout